# Generated by Django 4.1.7 on 2023-03-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('releaseDate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('company', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
