# Generated by Django 4.1.7 on 2023-03-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0002_videogame_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogame',
            old_name='releaseDate',
            new_name='releaseYear',
        ),
    ]
