# Generated by Django 4.1.7 on 2023-03-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0003_rename_releasedate_videogame_releaseyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videogame',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
