# Generated by Django 4.1.7 on 2023-03-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0004_videogame_id_alter_videogame_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
