# Generated by Django 4.1.7 on 2023-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0007_delete_player_videogame_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, null=True)),
                ('age', models.PositiveSmallIntegerField(default=18)),
                ('email', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(default='NB', max_length=2)),
                ('favouriteGenre', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
