# Generated by Django 4.1.7 on 2023-03-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0009_platform_user_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='user',
        ),
    ]
