# Generated by Django 4.1.7 on 2023-03-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0011_alter_platform_model_alter_player_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='model',
        ),
        migrations.AddField(
            model_name='platform',
            name='size',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
