# Generated by Django 4.1.7 on 2023-03-19 22:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0013_alter_platform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hoursPlayed', models.SmallIntegerField(default=0)),
                ('hasSaveFile', models.BooleanField(default=False)),
                ('gamename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames_api.videogame')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames_api.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='players',
            field=models.ManyToManyField(through='videogames_api.PlayerGame', to='videogames_api.videogame'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='games',
            field=models.ManyToManyField(through='videogames_api.PlayerGame', to='videogames_api.player'),
        ),
    ]
