# Generated by Django 4.1.7 on 2023-03-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0014_playergame_player_players_videogame_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='players',
            new_name='games',
        ),
        migrations.RenameField(
            model_name='videogame',
            old_name='games',
            new_name='players',
        ),
    ]
