# Generated by Django 4.1.7 on 2023-04-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0015_rename_players_player_games_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='games',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='players',
        ),
    ]
